MERGE INTO public.users (user_id,email,login,name,birthday)
VALUES (1,'mail1@.dd','login1','name',DATE '2000-10-10');

MERGE INTO public.users (user_id,email,login,name,birthday)
VALUES (2,'mail2@.dd','login2','name',DATE '2000-10-10');

MERGE INTO public.users (user_id,email,login,name,birthday)
VALUES (3,'mail3@.dd','login3','name',DATE '2000-10-10');

MERGE INTO public.users (user_id,email,login,name,birthday)
VALUES (4,'mail4@.dd','login4','name',DATE '2000-10-10');

MERGE INTO FRIENDSHIP_STATUS  (FRIENDSHIP_STATUS_ID,FRIENDSHIP_STATUS_NAME)
VALUES (1,'NOT_ACCEPTED');
MERGE INTO FRIENDSHIP_STATUS  (FRIENDSHIP_STATUS_ID,FRIENDSHIP_STATUS_NAME)
VALUES (2,'ACCEPTED');

TRUNCATE TABLE FRIENDS_LIST;

INSERT INTO FRIENDS_LIST (USER_ID,FRIEND_ID,FRIENDSHIP_STATUS_ID)
VALUES (2,1,2);
INSERT INTO FRIENDS_LIST (USER_ID,FRIEND_ID,FRIENDSHIP_STATUS_ID)
VALUES (1,2,2);
INSERT INTO FRIENDS_LIST (USER_ID,FRIEND_ID,FRIENDSHIP_STATUS_ID)
VALUES (1,3,2);
INSERT INTO FRIENDS_LIST (USER_ID,FRIEND_ID,FRIENDSHIP_STATUS_ID)
VALUES (3,1,2);
INSERT INTO FRIENDS_LIST (USER_ID,FRIEND_ID,FRIENDSHIP_STATUS_ID)
VALUES (2,3,1);
INSERT INTO FRIENDS_LIST (USER_ID,FRIEND_ID,FRIENDSHIP_STATUS_ID)
VALUES (3,2,1);



MERGE INTO GENRE  (GENRE_ID,GENRE_NAME)
VALUES (1,'Comedy');
MERGE INTO GENRE  (GENRE_ID,GENRE_NAME)
VALUES (2,'Drama');
MERGE INTO GENRE  (GENRE_ID,GENRE_NAME)
VALUES (3,'Cartoon');
MERGE INTO GENRE  (GENRE_ID,GENRE_NAME)
VALUES (4,'Thriller');
MERGE INTO GENRE  (GENRE_ID,GENRE_NAME)
VALUES (5,'Documentary');
MERGE INTO GENRE  (GENRE_ID,GENRE_NAME)
VALUES (6,'Action');

MERGE INTO RATING_MPA (RATING_MPA_ID,RATING_MPA_NAME)
VALUES (1,'G');
MERGE INTO RATING_MPA (RATING_MPA_ID,RATING_MPA_NAME)
VALUES (2,'PG');
MERGE INTO RATING_MPA (RATING_MPA_ID,RATING_MPA_NAME)
VALUES (3,'PG-13');
MERGE INTO RATING_MPA (RATING_MPA_ID,RATING_MPA_NAME)
VALUES (4,'R');
MERGE INTO RATING_MPA (RATING_MPA_ID,RATING_MPA_NAME)
VALUES (5,'NC-17');

MERGE INTO public.films (film_id,name,description,release_date,duration,rating_mpa_id)
VALUES (1,'film1','d1',DATE '2000-10-10',10,1);

MERGE INTO public.films (film_id,name,description,release_date,duration,rating_mpa_id)
VALUES (2,'film2','d2',DATE '2000-10-12',12,2);

MERGE INTO public.films (film_id,name,description,release_date,duration,rating_mpa_id)
VALUES (3,'film3','d3',DATE '2000-10-13',13,3);

MERGE INTO public.films (film_id,name,description,release_date,duration,rating_mpa_id)
VALUES (4,'film4','d4',DATE '2000-10-14',14,4);

TRUNCATE TABLE LIKED_FILMS;
INSERT INTO LIKED_FILMS (USER_ID,FILM_ID)
VALUES (1,1);
INSERT INTO LIKED_FILMS (USER_ID,FILM_ID)
VALUES (1,2);
INSERT INTO LIKED_FILMS (USER_ID,FILM_ID)
VALUES (2,1);
INSERT INTO LIKED_FILMS (USER_ID,FILM_ID)
VALUES (3,3);

TRUNCATE TABLE FILMS_TO_GENRES;
INSERT INTO FILMS_TO_GENRES (FILM_ID,GENRE_ID)
VALUES (1,1);
INSERT INTO FILMS_TO_GENRES (FILM_ID,GENRE_ID)
VALUES (1,2);
INSERT INTO FILMS_TO_GENRES (FILM_ID,GENRE_ID)
VALUES (2,3);
INSERT INTO FILMS_TO_GENRES (FILM_ID,GENRE_ID)
VALUES (3,1);
INSERT INTO FILMS_TO_GENRES (FILM_ID,GENRE_ID)
VALUES (4,4);
INSERT INTO FILMS_TO_GENRES (FILM_ID,GENRE_ID)
VALUES (4,2);
