MERGE INTO GENRE  (GENRE_ID,GENRE_NAME)
VALUES (1,'Комедия');
MERGE INTO GENRE  (GENRE_ID,GENRE_NAME)
VALUES (2,'Драма');
MERGE INTO GENRE  (GENRE_ID,GENRE_NAME)
VALUES (3,'Мультфильм');
MERGE INTO GENRE  (GENRE_ID,GENRE_NAME)
VALUES (4,'Триллер');
MERGE INTO GENRE  (GENRE_ID,GENRE_NAME)
VALUES (5,'Документальный');
MERGE INTO GENRE  (GENRE_ID,GENRE_NAME)
VALUES (6,'Боевик');

MERGE INTO RATING_MPA (RATING_MPA_ID,RATING_MPA_NAME)
VALUES (1,'G');
MERGE INTO RATING_MPA (RATING_MPA_ID,RATING_MPA_NAME)
VALUES (2,'PG');
MERGE INTO RATING_MPA (RATING_MPA_ID,RATING_MPA_NAME)
VALUES (3,'PG-13');
MERGE INTO RATING_MPA (RATING_MPA_ID,RATING_MPA_NAME)
VALUES (4,'R');
MERGE INTO RATING_MPA (RATING_MPA_ID,RATING_MPA_NAME)
VALUES (5,'NC-17');

MERGE INTO FRIENDSHIP_STATUS  (FRIENDSHIP_STATUS_ID,FRIENDSHIP_STATUS_NAME)
VALUES (1,'NOT_ACCEPTED');
MERGE INTO FRIENDSHIP_STATUS  (FRIENDSHIP_STATUS_ID,FRIENDSHIP_STATUS_NAME)
VALUES (2,'ACCEPTED');